FROM alpine:latest

WORKDIR /app

# Copiar o binário pré-compilado do diretório de build
COPY build/scheduler /app/scheduler

# Dar permissão de execução
RUN chmod +x /app/scheduler

# Iniciar o serviço
CMD ["./scheduler"]
