FROM alpine:latest

RUN apk add --no-cache libstdc++ libgcc

WORKDIR /app

# Copiar o binário pré-compilado do diretório de build
COPY build/workers /app/worker

# Dar permissão de execução
RUN chmod +x /app/worker

# Iniciar o serviço
CMD ["./worker"]
