FROM alpine:latest

RUN apk add --no-cache libstdc++ libgcc

WORKDIR /app

# Copiar o binário pré-compilado do diretório de build
COPY dist/scheduler /app/scheduler

# Dar permissão de execução
RUN chmod +x /app/scheduler

# Iniciar o serviço
CMD ["./scheduler"]
